### ISSUE TITLE
Cask cannot bootstrap in Emacs 26 on Travis.

### ISSUE THREAD

**Issue by DarwinAwardWinner** [cask/cask#417]
My Travis test runs have been failing on Emacs 26 with the following log: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/jobs/342447253

As you can see here, this failure only occurs on emacs-26-pretest and emacs-git-snapshot: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/builds/342447247

The error messages are not very clear, but the lines that stick out to me are:

    Opening TLS connection to ‘elpa.gnu.org’...failed
    Failed to download ‘gnu’ archive.
    Package ‘s-’ is unavailable

Here's my Travis config, which just installs cask the usual way: https://github.com/DarwinAwardWinner/ido-completing-read-plus/blob/master/.travis.yml#L31

**Comment by sambrightman** [comment]
There are changes to SSL defaults in Emacs 26 which make it more strict. However, the elpa.gnu.org certificate has an issue which prevents GnuTLS < 3 from working with it. I'm in contact with sysadmins there to try to fix it.

**Comment by sambrightman** [comment]
In co-operation with the sysadmin there, I believe this issue is now fixed. Could you confirm?

**Comment by DarwinAwardWinner** [comment]
It looks like I'm still seeing the same problem: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/jobs/342454678

**Comment by sambrightman** [comment]
Hmm, current Emacs 26 doesn’t have GnuTLS support and I’ve seen before that `gnutls-cli` not being installed shows up like any other failure in the messages. With support for insecure `openssl s_client` removed, I can see how this would still fail for now. See #

**Comment by sambrightman** [comment]
There is a new 26 pretest released which should have the appropriate GnuTLS support built-in.

**Comment by DarwinAwardWinner** [comment]
That seems to have fixed it: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/jobs/342454678

However, emacs-git-snapshot now hangs indefinitely: https://travis-ci.org/DarwinAwardWinner/ido-completing-read-plus/jobs/342454679. I don't know if this has anything to do with cask or not. It might simply be an incompatibility between emacs-git-snapshot and my package or my package's test suite.

**Comment by sambrightman** [comment]
It could be some unrelated issue with the current snapshot, or it could be waiting for input because something is still wrong with HTTPS verification (the network security manager has a tendency to hang waiting for input).

**Comment by DarwinAwardWinner** [comment]
Well, it hangs when running the test suite, which shouldn't be making any network connections.

**Comment by sambrightman** [comment]
Okay, closing this for now. If you have some idea what is causing the hang then we can either open another issue or re-release an updated master snapshot later.

**Comment by Silex** [comment]
I have the same problem, but it appeared yesterday https://travis-ci.org/Silex/docker-emacs/jobs/346742098

**Comment by Silex** [comment]
Ah, might be related to https://github.com/melpa/melpa/issues/5339
